title: Georg Vetter
email: georg.vetter.privat@gmail.com
logo: /assets/Georg - 2- HQ.jpg
description: >
<br>Data Scientist <br><br> <a href="https://medium.com/@georg.vetter.privat"> View my Medium Profile</a>
theme: jekyll-theme-minimal
